//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Packages.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cel.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffli" +
            "ne")]
        public string Packages_AutorizacionComprobantesProduccion_AutorizacionComprobantesOfflineService {
            get {
                return ((string)(this["Packages_AutorizacionComprobantesProduccion_AutorizacionComprobantesOfflineServic" +
                    "e"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://celcer.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOf" +
            "fline")]
        public string Packages_AutorizacionComprobantesPruebas_AutorizacionComprobantesOfflineService {
            get {
                return ((string)(this["Packages_AutorizacionComprobantesPruebas_AutorizacionComprobantesOfflineService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cel.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline")]
        public string Packages_RecepcionComprobantesProduccion_RecepcionComprobantesOfflineService {
            get {
                return ((string)(this["Packages_RecepcionComprobantesProduccion_RecepcionComprobantesOfflineService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://celcer.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffli" +
            "ne")]
        public string Packages_RecepcionComprobantesPruebas_RecepcionComprobantesOfflineService {
            get {
                return ((string)(this["Packages_RecepcionComprobantesPruebas_RecepcionComprobantesOfflineService"]));
            }
        }
    }
}
