//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://celcer.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantes")]
        public string WebUI_ec_gob_sri_celcer_RecepcionComprobantesService {
            get {
                return ((string)(this["WebUI_ec_gob_sri_celcer_RecepcionComprobantesService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://celcer.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantes")]
        public string WebUI_ec_gob_sri_celcer1_AutorizacionComprobantesService {
            get {
                return ((string)(this["WebUI_ec_gob_sri_celcer1_AutorizacionComprobantesService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://216.120.250.104/SICE/ws/Metodos.asmx")]
        public string WebUI_SICE_Metodos {
            get {
                return ((string)(this["WebUI_SICE_Metodos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cel.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantes")]
        public string WebUI_ec_gob_sri_cel_RecepcionComprobantesService {
            get {
                return ((string)(this["WebUI_ec_gob_sri_cel_RecepcionComprobantesService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cel.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantes")]
        public string WebUI_ec_gob_sri_cel1_AutorizacionComprobantesService {
            get {
                return ((string)(this["WebUI_ec_gob_sri_cel1_AutorizacionComprobantesService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://celcer.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffli" +
            "ne")]
        public string WebUI_ec_gob_sri_celcerOff_RecepcionComprobantesOfflineService {
            get {
                return ((string)(this["WebUI_ec_gob_sri_celcerOff_RecepcionComprobantesOfflineService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cel.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline")]
        public string WebUI_ec_gob_sri_celOff_RecepcionComprobantesOfflineService {
            get {
                return ((string)(this["WebUI_ec_gob_sri_celOff_RecepcionComprobantesOfflineService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cel.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffli" +
            "ne")]
        public string WebUI_ec_gob_sri_cel1Off_AutorizacionComprobantesOfflineService {
            get {
                return ((string)(this["WebUI_ec_gob_sri_cel1Off_AutorizacionComprobantesOfflineService"]));
            }
        }
    }
}
