//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebUI.SICE {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MetodosSoap", Namespace="http://tempuri.org/")]
    public partial class Metodos : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback SignUpOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreaUsuariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetClaveOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificarComprobantesOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecibirComprobanteObjOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecibirComprobanteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtieneAutorizacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarComprobanteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ResetComprobanteOperationCompleted;
        
        private System.Threading.SendOrPostCallback MailComprobanteOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificarComprobanteOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRespuestaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadComprobanteOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCabeceraListadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadComprobantesOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveEmpresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmpresasOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Metodos() {
            this.Url = global::WebUI.Properties.Settings.Default.WebUI_SICE_Metodos;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event SignUpCompletedEventHandler SignUpCompleted;
        
        /// <remarks/>
        public event CreaUsuariosCompletedEventHandler CreaUsuariosCompleted;
        
        /// <remarks/>
        public event SetClaveCompletedEventHandler SetClaveCompleted;
        
        /// <remarks/>
        public event VerificarComprobantesCompletedEventHandler VerificarComprobantesCompleted;
        
        /// <remarks/>
        public event RecibirComprobanteObjCompletedEventHandler RecibirComprobanteObjCompleted;
        
        /// <remarks/>
        public event RecibirComprobanteCompletedEventHandler RecibirComprobanteCompleted;
        
        /// <remarks/>
        public event ObtieneAutorizacionCompletedEventHandler ObtieneAutorizacionCompleted;
        
        /// <remarks/>
        public event EnviarComprobanteCompletedEventHandler EnviarComprobanteCompleted;
        
        /// <remarks/>
        public event ResetComprobanteCompletedEventHandler ResetComprobanteCompleted;
        
        /// <remarks/>
        public event MailComprobanteCompletedEventHandler MailComprobanteCompleted;
        
        /// <remarks/>
        public event VerificarComprobanteCompletedEventHandler VerificarComprobanteCompleted;
        
        /// <remarks/>
        public event GetRespuestaCompletedEventHandler GetRespuestaCompleted;
        
        /// <remarks/>
        public event GetXMLCompletedEventHandler GetXMLCompleted;
        
        /// <remarks/>
        public event UploadComprobanteCompletedEventHandler UploadComprobanteCompleted;
        
        /// <remarks/>
        public event GetCabeceraListadoCompletedEventHandler GetCabeceraListadoCompleted;
        
        /// <remarks/>
        public event LoadComprobantesCompletedEventHandler LoadComprobantesCompleted;
        
        /// <remarks/>
        public event SaveEmpresaCompletedEventHandler SaveEmpresaCompleted;
        
        /// <remarks/>
        public event GetEmpresasCompletedEventHandler GetEmpresasCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Login(object objeto) {
            object[] results = this.Invoke("Login", new object[] {
                        objeto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(object objeto) {
            this.LoginAsync(objeto, null);
        }
        
        /// <remarks/>
        public void LoginAsync(object objeto, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        objeto}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SignUp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SignUp(object objeto) {
            object[] results = this.Invoke("SignUp", new object[] {
                        objeto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SignUpAsync(object objeto) {
            this.SignUpAsync(objeto, null);
        }
        
        /// <remarks/>
        public void SignUpAsync(object objeto, object userState) {
            if ((this.SignUpOperationCompleted == null)) {
                this.SignUpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSignUpOperationCompleted);
            }
            this.InvokeAsync("SignUp", new object[] {
                        objeto}, this.SignUpOperationCompleted, userState);
        }
        
        private void OnSignUpOperationCompleted(object arg) {
            if ((this.SignUpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SignUpCompleted(this, new SignUpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreaUsuarios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreaUsuarios(object objeto) {
            object[] results = this.Invoke("CreaUsuarios", new object[] {
                        objeto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreaUsuariosAsync(object objeto) {
            this.CreaUsuariosAsync(objeto, null);
        }
        
        /// <remarks/>
        public void CreaUsuariosAsync(object objeto, object userState) {
            if ((this.CreaUsuariosOperationCompleted == null)) {
                this.CreaUsuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreaUsuariosOperationCompleted);
            }
            this.InvokeAsync("CreaUsuarios", new object[] {
                        objeto}, this.CreaUsuariosOperationCompleted, userState);
        }
        
        private void OnCreaUsuariosOperationCompleted(object arg) {
            if ((this.CreaUsuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreaUsuariosCompleted(this, new CreaUsuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetClave", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetClave(object objeto) {
            object[] results = this.Invoke("SetClave", new object[] {
                        objeto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetClaveAsync(object objeto) {
            this.SetClaveAsync(objeto, null);
        }
        
        /// <remarks/>
        public void SetClaveAsync(object objeto, object userState) {
            if ((this.SetClaveOperationCompleted == null)) {
                this.SetClaveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetClaveOperationCompleted);
            }
            this.InvokeAsync("SetClave", new object[] {
                        objeto}, this.SetClaveOperationCompleted, userState);
        }
        
        private void OnSetClaveOperationCompleted(object arg) {
            if ((this.SetClaveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetClaveCompleted(this, new SetClaveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerificarComprobantes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VerificarComprobantes() {
            object[] results = this.Invoke("VerificarComprobantes", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VerificarComprobantesAsync() {
            this.VerificarComprobantesAsync(null);
        }
        
        /// <remarks/>
        public void VerificarComprobantesAsync(object userState) {
            if ((this.VerificarComprobantesOperationCompleted == null)) {
                this.VerificarComprobantesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificarComprobantesOperationCompleted);
            }
            this.InvokeAsync("VerificarComprobantes", new object[0], this.VerificarComprobantesOperationCompleted, userState);
        }
        
        private void OnVerificarComprobantesOperationCompleted(object arg) {
            if ((this.VerificarComprobantesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificarComprobantesCompleted(this, new VerificarComprobantesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecibirComprobanteObj", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RecibirComprobanteObj(object objeto) {
            object[] results = this.Invoke("RecibirComprobanteObj", new object[] {
                        objeto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecibirComprobanteObjAsync(object objeto) {
            this.RecibirComprobanteObjAsync(objeto, null);
        }
        
        /// <remarks/>
        public void RecibirComprobanteObjAsync(object objeto, object userState) {
            if ((this.RecibirComprobanteObjOperationCompleted == null)) {
                this.RecibirComprobanteObjOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecibirComprobanteObjOperationCompleted);
            }
            this.InvokeAsync("RecibirComprobanteObj", new object[] {
                        objeto}, this.RecibirComprobanteObjOperationCompleted, userState);
        }
        
        private void OnRecibirComprobanteObjOperationCompleted(object arg) {
            if ((this.RecibirComprobanteObjCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecibirComprobanteObjCompleted(this, new RecibirComprobanteObjCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecibirComprobante", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RecibirComprobante(string xml, string mail, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> formato) {
            object[] results = this.Invoke("RecibirComprobante", new object[] {
                        xml,
                        mail,
                        formato});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecibirComprobanteAsync(string xml, string mail, System.Nullable<int> formato) {
            this.RecibirComprobanteAsync(xml, mail, formato, null);
        }
        
        /// <remarks/>
        public void RecibirComprobanteAsync(string xml, string mail, System.Nullable<int> formato, object userState) {
            if ((this.RecibirComprobanteOperationCompleted == null)) {
                this.RecibirComprobanteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecibirComprobanteOperationCompleted);
            }
            this.InvokeAsync("RecibirComprobante", new object[] {
                        xml,
                        mail,
                        formato}, this.RecibirComprobanteOperationCompleted, userState);
        }
        
        private void OnRecibirComprobanteOperationCompleted(object arg) {
            if ((this.RecibirComprobanteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecibirComprobanteCompleted(this, new RecibirComprobanteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtieneAutorizacion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObtieneAutorizacion(string clave) {
            object[] results = this.Invoke("ObtieneAutorizacion", new object[] {
                        clave});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtieneAutorizacionAsync(string clave) {
            this.ObtieneAutorizacionAsync(clave, null);
        }
        
        /// <remarks/>
        public void ObtieneAutorizacionAsync(string clave, object userState) {
            if ((this.ObtieneAutorizacionOperationCompleted == null)) {
                this.ObtieneAutorizacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtieneAutorizacionOperationCompleted);
            }
            this.InvokeAsync("ObtieneAutorizacion", new object[] {
                        clave}, this.ObtieneAutorizacionOperationCompleted, userState);
        }
        
        private void OnObtieneAutorizacionOperationCompleted(object arg) {
            if ((this.ObtieneAutorizacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtieneAutorizacionCompleted(this, new ObtieneAutorizacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarComprobante", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnviarComprobante(object objeto) {
            object[] results = this.Invoke("EnviarComprobante", new object[] {
                        objeto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarComprobanteAsync(object objeto) {
            this.EnviarComprobanteAsync(objeto, null);
        }
        
        /// <remarks/>
        public void EnviarComprobanteAsync(object objeto, object userState) {
            if ((this.EnviarComprobanteOperationCompleted == null)) {
                this.EnviarComprobanteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarComprobanteOperationCompleted);
            }
            this.InvokeAsync("EnviarComprobante", new object[] {
                        objeto}, this.EnviarComprobanteOperationCompleted, userState);
        }
        
        private void OnEnviarComprobanteOperationCompleted(object arg) {
            if ((this.EnviarComprobanteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarComprobanteCompleted(this, new EnviarComprobanteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ResetComprobante", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ResetComprobante(object objeto) {
            object[] results = this.Invoke("ResetComprobante", new object[] {
                        objeto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ResetComprobanteAsync(object objeto) {
            this.ResetComprobanteAsync(objeto, null);
        }
        
        /// <remarks/>
        public void ResetComprobanteAsync(object objeto, object userState) {
            if ((this.ResetComprobanteOperationCompleted == null)) {
                this.ResetComprobanteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResetComprobanteOperationCompleted);
            }
            this.InvokeAsync("ResetComprobante", new object[] {
                        objeto}, this.ResetComprobanteOperationCompleted, userState);
        }
        
        private void OnResetComprobanteOperationCompleted(object arg) {
            if ((this.ResetComprobanteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResetComprobanteCompleted(this, new ResetComprobanteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MailComprobante", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MailComprobante(object objeto) {
            object[] results = this.Invoke("MailComprobante", new object[] {
                        objeto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MailComprobanteAsync(object objeto) {
            this.MailComprobanteAsync(objeto, null);
        }
        
        /// <remarks/>
        public void MailComprobanteAsync(object objeto, object userState) {
            if ((this.MailComprobanteOperationCompleted == null)) {
                this.MailComprobanteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMailComprobanteOperationCompleted);
            }
            this.InvokeAsync("MailComprobante", new object[] {
                        objeto}, this.MailComprobanteOperationCompleted, userState);
        }
        
        private void OnMailComprobanteOperationCompleted(object arg) {
            if ((this.MailComprobanteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MailComprobanteCompleted(this, new MailComprobanteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerificarComprobante", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VerificarComprobante(string clave) {
            object[] results = this.Invoke("VerificarComprobante", new object[] {
                        clave});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VerificarComprobanteAsync(string clave) {
            this.VerificarComprobanteAsync(clave, null);
        }
        
        /// <remarks/>
        public void VerificarComprobanteAsync(string clave, object userState) {
            if ((this.VerificarComprobanteOperationCompleted == null)) {
                this.VerificarComprobanteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificarComprobanteOperationCompleted);
            }
            this.InvokeAsync("VerificarComprobante", new object[] {
                        clave}, this.VerificarComprobanteOperationCompleted, userState);
        }
        
        private void OnVerificarComprobanteOperationCompleted(object arg) {
            if ((this.VerificarComprobanteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificarComprobanteCompleted(this, new VerificarComprobanteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRespuesta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetRespuesta(string clave) {
            object[] results = this.Invoke("GetRespuesta", new object[] {
                        clave});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRespuestaAsync(string clave) {
            this.GetRespuestaAsync(clave, null);
        }
        
        /// <remarks/>
        public void GetRespuestaAsync(string clave, object userState) {
            if ((this.GetRespuestaOperationCompleted == null)) {
                this.GetRespuestaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRespuestaOperationCompleted);
            }
            this.InvokeAsync("GetRespuesta", new object[] {
                        clave}, this.GetRespuestaOperationCompleted, userState);
        }
        
        private void OnGetRespuestaOperationCompleted(object arg) {
            if ((this.GetRespuestaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRespuestaCompleted(this, new GetRespuestaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetXML", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetXML(string clave) {
            object[] results = this.Invoke("GetXML", new object[] {
                        clave});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetXMLAsync(string clave) {
            this.GetXMLAsync(clave, null);
        }
        
        /// <remarks/>
        public void GetXMLAsync(string clave, object userState) {
            if ((this.GetXMLOperationCompleted == null)) {
                this.GetXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetXMLOperationCompleted);
            }
            this.InvokeAsync("GetXML", new object[] {
                        clave}, this.GetXMLOperationCompleted, userState);
        }
        
        private void OnGetXMLOperationCompleted(object arg) {
            if ((this.GetXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetXMLCompleted(this, new GetXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadComprobante", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UploadComprobante(object objeto) {
            object[] results = this.Invoke("UploadComprobante", new object[] {
                        objeto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UploadComprobanteAsync(object objeto) {
            this.UploadComprobanteAsync(objeto, null);
        }
        
        /// <remarks/>
        public void UploadComprobanteAsync(object objeto, object userState) {
            if ((this.UploadComprobanteOperationCompleted == null)) {
                this.UploadComprobanteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadComprobanteOperationCompleted);
            }
            this.InvokeAsync("UploadComprobante", new object[] {
                        objeto}, this.UploadComprobanteOperationCompleted, userState);
        }
        
        private void OnUploadComprobanteOperationCompleted(object arg) {
            if ((this.UploadComprobanteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadComprobanteCompleted(this, new UploadComprobanteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCabeceraListado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCabeceraListado(object objeto) {
            object[] results = this.Invoke("GetCabeceraListado", new object[] {
                        objeto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCabeceraListadoAsync(object objeto) {
            this.GetCabeceraListadoAsync(objeto, null);
        }
        
        /// <remarks/>
        public void GetCabeceraListadoAsync(object objeto, object userState) {
            if ((this.GetCabeceraListadoOperationCompleted == null)) {
                this.GetCabeceraListadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCabeceraListadoOperationCompleted);
            }
            this.InvokeAsync("GetCabeceraListado", new object[] {
                        objeto}, this.GetCabeceraListadoOperationCompleted, userState);
        }
        
        private void OnGetCabeceraListadoOperationCompleted(object arg) {
            if ((this.GetCabeceraListadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCabeceraListadoCompleted(this, new GetCabeceraListadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoadComprobantes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LoadComprobantes(object objeto) {
            object[] results = this.Invoke("LoadComprobantes", new object[] {
                        objeto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoadComprobantesAsync(object objeto) {
            this.LoadComprobantesAsync(objeto, null);
        }
        
        /// <remarks/>
        public void LoadComprobantesAsync(object objeto, object userState) {
            if ((this.LoadComprobantesOperationCompleted == null)) {
                this.LoadComprobantesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadComprobantesOperationCompleted);
            }
            this.InvokeAsync("LoadComprobantes", new object[] {
                        objeto}, this.LoadComprobantesOperationCompleted, userState);
        }
        
        private void OnLoadComprobantesOperationCompleted(object arg) {
            if ((this.LoadComprobantesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadComprobantesCompleted(this, new LoadComprobantesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveEmpresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SaveEmpresa(object objeto) {
            object[] results = this.Invoke("SaveEmpresa", new object[] {
                        objeto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SaveEmpresaAsync(object objeto) {
            this.SaveEmpresaAsync(objeto, null);
        }
        
        /// <remarks/>
        public void SaveEmpresaAsync(object objeto, object userState) {
            if ((this.SaveEmpresaOperationCompleted == null)) {
                this.SaveEmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveEmpresaOperationCompleted);
            }
            this.InvokeAsync("SaveEmpresa", new object[] {
                        objeto}, this.SaveEmpresaOperationCompleted, userState);
        }
        
        private void OnSaveEmpresaOperationCompleted(object arg) {
            if ((this.SaveEmpresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveEmpresaCompleted(this, new SaveEmpresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEmpresas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetEmpresas(object objeto) {
            object[] results = this.Invoke("GetEmpresas", new object[] {
                        objeto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetEmpresasAsync(object objeto) {
            this.GetEmpresasAsync(objeto, null);
        }
        
        /// <remarks/>
        public void GetEmpresasAsync(object objeto, object userState) {
            if ((this.GetEmpresasOperationCompleted == null)) {
                this.GetEmpresasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmpresasOperationCompleted);
            }
            this.InvokeAsync("GetEmpresas", new object[] {
                        objeto}, this.GetEmpresasOperationCompleted, userState);
        }
        
        private void OnGetEmpresasOperationCompleted(object arg) {
            if ((this.GetEmpresasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmpresasCompleted(this, new GetEmpresasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void SignUpCompletedEventHandler(object sender, SignUpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SignUpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SignUpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void CreaUsuariosCompletedEventHandler(object sender, CreaUsuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreaUsuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreaUsuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void SetClaveCompletedEventHandler(object sender, SetClaveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetClaveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetClaveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void VerificarComprobantesCompletedEventHandler(object sender, VerificarComprobantesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificarComprobantesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificarComprobantesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void RecibirComprobanteObjCompletedEventHandler(object sender, RecibirComprobanteObjCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecibirComprobanteObjCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecibirComprobanteObjCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void RecibirComprobanteCompletedEventHandler(object sender, RecibirComprobanteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecibirComprobanteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecibirComprobanteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ObtieneAutorizacionCompletedEventHandler(object sender, ObtieneAutorizacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtieneAutorizacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtieneAutorizacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void EnviarComprobanteCompletedEventHandler(object sender, EnviarComprobanteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarComprobanteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarComprobanteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ResetComprobanteCompletedEventHandler(object sender, ResetComprobanteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResetComprobanteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ResetComprobanteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void MailComprobanteCompletedEventHandler(object sender, MailComprobanteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MailComprobanteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MailComprobanteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void VerificarComprobanteCompletedEventHandler(object sender, VerificarComprobanteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificarComprobanteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificarComprobanteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetRespuestaCompletedEventHandler(object sender, GetRespuestaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRespuestaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRespuestaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetXMLCompletedEventHandler(object sender, GetXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void UploadComprobanteCompletedEventHandler(object sender, UploadComprobanteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadComprobanteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadComprobanteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetCabeceraListadoCompletedEventHandler(object sender, GetCabeceraListadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCabeceraListadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCabeceraListadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void LoadComprobantesCompletedEventHandler(object sender, LoadComprobantesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadComprobantesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadComprobantesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void SaveEmpresaCompletedEventHandler(object sender, SaveEmpresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveEmpresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveEmpresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetEmpresasCompletedEventHandler(object sender, GetEmpresasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmpresasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmpresasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591