//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinServiceSICE.SICE {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SICE.MetodosSoap")]
    public interface MetodosSoap {
        
        // CODEGEN: Generating message contract since element name objeto from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetClave", ReplyAction="*")]
        WinServiceSICE.SICE.SetClaveResponse SetClave(WinServiceSICE.SICE.SetClaveRequest request);
        
        // CODEGEN: Generating message contract since element name VerificarComprobantesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarComprobantes", ReplyAction="*")]
        WinServiceSICE.SICE.VerificarComprobantesResponse VerificarComprobantes(WinServiceSICE.SICE.VerificarComprobantesRequest request);
        
        // CODEGEN: Generating message contract since element name xml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecibirComprobante", ReplyAction="*")]
        WinServiceSICE.SICE.RecibirComprobanteResponse RecibirComprobante(WinServiceSICE.SICE.RecibirComprobanteRequest request);
        
        // CODEGEN: Generating message contract since element name objeto from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviarComprobante", ReplyAction="*")]
        WinServiceSICE.SICE.EnviarComprobanteResponse EnviarComprobante(WinServiceSICE.SICE.EnviarComprobanteRequest request);
        
        // CODEGEN: Generating message contract since element name objeto from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResetComprobante", ReplyAction="*")]
        WinServiceSICE.SICE.ResetComprobanteResponse ResetComprobante(WinServiceSICE.SICE.ResetComprobanteRequest request);
        
        // CODEGEN: Generating message contract since element name clave from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarComprobante", ReplyAction="*")]
        WinServiceSICE.SICE.VerificarComprobanteResponse VerificarComprobante(WinServiceSICE.SICE.VerificarComprobanteRequest request);
        
        // CODEGEN: Generating message contract since element name clave from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRespuesta", ReplyAction="*")]
        WinServiceSICE.SICE.GetRespuestaResponse GetRespuesta(WinServiceSICE.SICE.GetRespuestaRequest request);
        
        // CODEGEN: Generating message contract since element name xml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadComprobante", ReplyAction="*")]
        WinServiceSICE.SICE.UploadComprobanteResponse UploadComprobante(WinServiceSICE.SICE.UploadComprobanteRequest request);
        
        // CODEGEN: Generating message contract since element name objeto from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadComprobantes", ReplyAction="*")]
        WinServiceSICE.SICE.LoadComprobantesResponse LoadComprobantes(WinServiceSICE.SICE.LoadComprobantesRequest request);
        
        // CODEGEN: Generating message contract since element name objeto from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveEmpresa", ReplyAction="*")]
        WinServiceSICE.SICE.SaveEmpresaResponse SaveEmpresa(WinServiceSICE.SICE.SaveEmpresaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetClaveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetClave", Namespace="http://tempuri.org/", Order=0)]
        public WinServiceSICE.SICE.SetClaveRequestBody Body;
        
        public SetClaveRequest() {
        }
        
        public SetClaveRequest(WinServiceSICE.SICE.SetClaveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetClaveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object objeto;
        
        public SetClaveRequestBody() {
        }
        
        public SetClaveRequestBody(object objeto) {
            this.objeto = objeto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetClaveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetClaveResponse", Namespace="http://tempuri.org/", Order=0)]
        public WinServiceSICE.SICE.SetClaveResponseBody Body;
        
        public SetClaveResponse() {
        }
        
        public SetClaveResponse(WinServiceSICE.SICE.SetClaveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetClaveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetClaveResult;
        
        public SetClaveResponseBody() {
        }
        
        public SetClaveResponseBody(string SetClaveResult) {
            this.SetClaveResult = SetClaveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarComprobantesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarComprobantes", Namespace="http://tempuri.org/", Order=0)]
        public WinServiceSICE.SICE.VerificarComprobantesRequestBody Body;
        
        public VerificarComprobantesRequest() {
        }
        
        public VerificarComprobantesRequest(WinServiceSICE.SICE.VerificarComprobantesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class VerificarComprobantesRequestBody {
        
        public VerificarComprobantesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarComprobantesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarComprobantesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WinServiceSICE.SICE.VerificarComprobantesResponseBody Body;
        
        public VerificarComprobantesResponse() {
        }
        
        public VerificarComprobantesResponse(WinServiceSICE.SICE.VerificarComprobantesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarComprobantesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VerificarComprobantesResult;
        
        public VerificarComprobantesResponseBody() {
        }
        
        public VerificarComprobantesResponseBody(string VerificarComprobantesResult) {
            this.VerificarComprobantesResult = VerificarComprobantesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecibirComprobanteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecibirComprobante", Namespace="http://tempuri.org/", Order=0)]
        public WinServiceSICE.SICE.RecibirComprobanteRequestBody Body;
        
        public RecibirComprobanteRequest() {
        }
        
        public RecibirComprobanteRequest(WinServiceSICE.SICE.RecibirComprobanteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RecibirComprobanteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public RecibirComprobanteRequestBody() {
        }
        
        public RecibirComprobanteRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecibirComprobanteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecibirComprobanteResponse", Namespace="http://tempuri.org/", Order=0)]
        public WinServiceSICE.SICE.RecibirComprobanteResponseBody Body;
        
        public RecibirComprobanteResponse() {
        }
        
        public RecibirComprobanteResponse(WinServiceSICE.SICE.RecibirComprobanteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RecibirComprobanteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RecibirComprobanteResult;
        
        public RecibirComprobanteResponseBody() {
        }
        
        public RecibirComprobanteResponseBody(string RecibirComprobanteResult) {
            this.RecibirComprobanteResult = RecibirComprobanteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarComprobanteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarComprobante", Namespace="http://tempuri.org/", Order=0)]
        public WinServiceSICE.SICE.EnviarComprobanteRequestBody Body;
        
        public EnviarComprobanteRequest() {
        }
        
        public EnviarComprobanteRequest(WinServiceSICE.SICE.EnviarComprobanteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviarComprobanteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object objeto;
        
        public EnviarComprobanteRequestBody() {
        }
        
        public EnviarComprobanteRequestBody(object objeto) {
            this.objeto = objeto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarComprobanteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarComprobanteResponse", Namespace="http://tempuri.org/", Order=0)]
        public WinServiceSICE.SICE.EnviarComprobanteResponseBody Body;
        
        public EnviarComprobanteResponse() {
        }
        
        public EnviarComprobanteResponse(WinServiceSICE.SICE.EnviarComprobanteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviarComprobanteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EnviarComprobanteResult;
        
        public EnviarComprobanteResponseBody() {
        }
        
        public EnviarComprobanteResponseBody(string EnviarComprobanteResult) {
            this.EnviarComprobanteResult = EnviarComprobanteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResetComprobanteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResetComprobante", Namespace="http://tempuri.org/", Order=0)]
        public WinServiceSICE.SICE.ResetComprobanteRequestBody Body;
        
        public ResetComprobanteRequest() {
        }
        
        public ResetComprobanteRequest(WinServiceSICE.SICE.ResetComprobanteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ResetComprobanteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object objeto;
        
        public ResetComprobanteRequestBody() {
        }
        
        public ResetComprobanteRequestBody(object objeto) {
            this.objeto = objeto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResetComprobanteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResetComprobanteResponse", Namespace="http://tempuri.org/", Order=0)]
        public WinServiceSICE.SICE.ResetComprobanteResponseBody Body;
        
        public ResetComprobanteResponse() {
        }
        
        public ResetComprobanteResponse(WinServiceSICE.SICE.ResetComprobanteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ResetComprobanteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ResetComprobanteResult;
        
        public ResetComprobanteResponseBody() {
        }
        
        public ResetComprobanteResponseBody(string ResetComprobanteResult) {
            this.ResetComprobanteResult = ResetComprobanteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarComprobanteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarComprobante", Namespace="http://tempuri.org/", Order=0)]
        public WinServiceSICE.SICE.VerificarComprobanteRequestBody Body;
        
        public VerificarComprobanteRequest() {
        }
        
        public VerificarComprobanteRequest(WinServiceSICE.SICE.VerificarComprobanteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarComprobanteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clave;
        
        public VerificarComprobanteRequestBody() {
        }
        
        public VerificarComprobanteRequestBody(string clave) {
            this.clave = clave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarComprobanteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarComprobanteResponse", Namespace="http://tempuri.org/", Order=0)]
        public WinServiceSICE.SICE.VerificarComprobanteResponseBody Body;
        
        public VerificarComprobanteResponse() {
        }
        
        public VerificarComprobanteResponse(WinServiceSICE.SICE.VerificarComprobanteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarComprobanteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VerificarComprobanteResult;
        
        public VerificarComprobanteResponseBody() {
        }
        
        public VerificarComprobanteResponseBody(string VerificarComprobanteResult) {
            this.VerificarComprobanteResult = VerificarComprobanteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRespuestaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRespuesta", Namespace="http://tempuri.org/", Order=0)]
        public WinServiceSICE.SICE.GetRespuestaRequestBody Body;
        
        public GetRespuestaRequest() {
        }
        
        public GetRespuestaRequest(WinServiceSICE.SICE.GetRespuestaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRespuestaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clave;
        
        public GetRespuestaRequestBody() {
        }
        
        public GetRespuestaRequestBody(string clave) {
            this.clave = clave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRespuestaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRespuestaResponse", Namespace="http://tempuri.org/", Order=0)]
        public WinServiceSICE.SICE.GetRespuestaResponseBody Body;
        
        public GetRespuestaResponse() {
        }
        
        public GetRespuestaResponse(WinServiceSICE.SICE.GetRespuestaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRespuestaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetRespuestaResult;
        
        public GetRespuestaResponseBody() {
        }
        
        public GetRespuestaResponseBody(string GetRespuestaResult) {
            this.GetRespuestaResult = GetRespuestaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadComprobanteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadComprobante", Namespace="http://tempuri.org/", Order=0)]
        public WinServiceSICE.SICE.UploadComprobanteRequestBody Body;
        
        public UploadComprobanteRequest() {
        }
        
        public UploadComprobanteRequest(WinServiceSICE.SICE.UploadComprobanteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadComprobanteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public UploadComprobanteRequestBody() {
        }
        
        public UploadComprobanteRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadComprobanteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadComprobanteResponse", Namespace="http://tempuri.org/", Order=0)]
        public WinServiceSICE.SICE.UploadComprobanteResponseBody Body;
        
        public UploadComprobanteResponse() {
        }
        
        public UploadComprobanteResponse(WinServiceSICE.SICE.UploadComprobanteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadComprobanteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadComprobanteResult;
        
        public UploadComprobanteResponseBody() {
        }
        
        public UploadComprobanteResponseBody(string UploadComprobanteResult) {
            this.UploadComprobanteResult = UploadComprobanteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadComprobantesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadComprobantes", Namespace="http://tempuri.org/", Order=0)]
        public WinServiceSICE.SICE.LoadComprobantesRequestBody Body;
        
        public LoadComprobantesRequest() {
        }
        
        public LoadComprobantesRequest(WinServiceSICE.SICE.LoadComprobantesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadComprobantesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object objeto;
        
        public LoadComprobantesRequestBody() {
        }
        
        public LoadComprobantesRequestBody(object objeto) {
            this.objeto = objeto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadComprobantesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadComprobantesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WinServiceSICE.SICE.LoadComprobantesResponseBody Body;
        
        public LoadComprobantesResponse() {
        }
        
        public LoadComprobantesResponse(WinServiceSICE.SICE.LoadComprobantesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadComprobantesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoadComprobantesResult;
        
        public LoadComprobantesResponseBody() {
        }
        
        public LoadComprobantesResponseBody(string LoadComprobantesResult) {
            this.LoadComprobantesResult = LoadComprobantesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveEmpresaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveEmpresa", Namespace="http://tempuri.org/", Order=0)]
        public WinServiceSICE.SICE.SaveEmpresaRequestBody Body;
        
        public SaveEmpresaRequest() {
        }
        
        public SaveEmpresaRequest(WinServiceSICE.SICE.SaveEmpresaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveEmpresaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object objeto;
        
        public SaveEmpresaRequestBody() {
        }
        
        public SaveEmpresaRequestBody(object objeto) {
            this.objeto = objeto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveEmpresaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveEmpresaResponse", Namespace="http://tempuri.org/", Order=0)]
        public WinServiceSICE.SICE.SaveEmpresaResponseBody Body;
        
        public SaveEmpresaResponse() {
        }
        
        public SaveEmpresaResponse(WinServiceSICE.SICE.SaveEmpresaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveEmpresaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SaveEmpresaResult;
        
        public SaveEmpresaResponseBody() {
        }
        
        public SaveEmpresaResponseBody(string SaveEmpresaResult) {
            this.SaveEmpresaResult = SaveEmpresaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MetodosSoapChannel : WinServiceSICE.SICE.MetodosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MetodosSoapClient : System.ServiceModel.ClientBase<WinServiceSICE.SICE.MetodosSoap>, WinServiceSICE.SICE.MetodosSoap {
        
        public MetodosSoapClient() {
        }
        
        public MetodosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MetodosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MetodosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MetodosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinServiceSICE.SICE.SetClaveResponse WinServiceSICE.SICE.MetodosSoap.SetClave(WinServiceSICE.SICE.SetClaveRequest request) {
            return base.Channel.SetClave(request);
        }
        
        public string SetClave(object objeto) {
            WinServiceSICE.SICE.SetClaveRequest inValue = new WinServiceSICE.SICE.SetClaveRequest();
            inValue.Body = new WinServiceSICE.SICE.SetClaveRequestBody();
            inValue.Body.objeto = objeto;
            WinServiceSICE.SICE.SetClaveResponse retVal = ((WinServiceSICE.SICE.MetodosSoap)(this)).SetClave(inValue);
            return retVal.Body.SetClaveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinServiceSICE.SICE.VerificarComprobantesResponse WinServiceSICE.SICE.MetodosSoap.VerificarComprobantes(WinServiceSICE.SICE.VerificarComprobantesRequest request) {
            return base.Channel.VerificarComprobantes(request);
        }
        
        public string VerificarComprobantes() {
            WinServiceSICE.SICE.VerificarComprobantesRequest inValue = new WinServiceSICE.SICE.VerificarComprobantesRequest();
            inValue.Body = new WinServiceSICE.SICE.VerificarComprobantesRequestBody();
            WinServiceSICE.SICE.VerificarComprobantesResponse retVal = ((WinServiceSICE.SICE.MetodosSoap)(this)).VerificarComprobantes(inValue);
            return retVal.Body.VerificarComprobantesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinServiceSICE.SICE.RecibirComprobanteResponse WinServiceSICE.SICE.MetodosSoap.RecibirComprobante(WinServiceSICE.SICE.RecibirComprobanteRequest request) {
            return base.Channel.RecibirComprobante(request);
        }
        
        public string RecibirComprobante(string xml) {
            WinServiceSICE.SICE.RecibirComprobanteRequest inValue = new WinServiceSICE.SICE.RecibirComprobanteRequest();
            inValue.Body = new WinServiceSICE.SICE.RecibirComprobanteRequestBody();
            inValue.Body.xml = xml;
            WinServiceSICE.SICE.RecibirComprobanteResponse retVal = ((WinServiceSICE.SICE.MetodosSoap)(this)).RecibirComprobante(inValue);
            return retVal.Body.RecibirComprobanteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinServiceSICE.SICE.EnviarComprobanteResponse WinServiceSICE.SICE.MetodosSoap.EnviarComprobante(WinServiceSICE.SICE.EnviarComprobanteRequest request) {
            return base.Channel.EnviarComprobante(request);
        }
        
        public string EnviarComprobante(object objeto) {
            WinServiceSICE.SICE.EnviarComprobanteRequest inValue = new WinServiceSICE.SICE.EnviarComprobanteRequest();
            inValue.Body = new WinServiceSICE.SICE.EnviarComprobanteRequestBody();
            inValue.Body.objeto = objeto;
            WinServiceSICE.SICE.EnviarComprobanteResponse retVal = ((WinServiceSICE.SICE.MetodosSoap)(this)).EnviarComprobante(inValue);
            return retVal.Body.EnviarComprobanteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinServiceSICE.SICE.ResetComprobanteResponse WinServiceSICE.SICE.MetodosSoap.ResetComprobante(WinServiceSICE.SICE.ResetComprobanteRequest request) {
            return base.Channel.ResetComprobante(request);
        }
        
        public string ResetComprobante(object objeto) {
            WinServiceSICE.SICE.ResetComprobanteRequest inValue = new WinServiceSICE.SICE.ResetComprobanteRequest();
            inValue.Body = new WinServiceSICE.SICE.ResetComprobanteRequestBody();
            inValue.Body.objeto = objeto;
            WinServiceSICE.SICE.ResetComprobanteResponse retVal = ((WinServiceSICE.SICE.MetodosSoap)(this)).ResetComprobante(inValue);
            return retVal.Body.ResetComprobanteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinServiceSICE.SICE.VerificarComprobanteResponse WinServiceSICE.SICE.MetodosSoap.VerificarComprobante(WinServiceSICE.SICE.VerificarComprobanteRequest request) {
            return base.Channel.VerificarComprobante(request);
        }
        
        public string VerificarComprobante(string clave) {
            WinServiceSICE.SICE.VerificarComprobanteRequest inValue = new WinServiceSICE.SICE.VerificarComprobanteRequest();
            inValue.Body = new WinServiceSICE.SICE.VerificarComprobanteRequestBody();
            inValue.Body.clave = clave;
            WinServiceSICE.SICE.VerificarComprobanteResponse retVal = ((WinServiceSICE.SICE.MetodosSoap)(this)).VerificarComprobante(inValue);
            return retVal.Body.VerificarComprobanteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinServiceSICE.SICE.GetRespuestaResponse WinServiceSICE.SICE.MetodosSoap.GetRespuesta(WinServiceSICE.SICE.GetRespuestaRequest request) {
            return base.Channel.GetRespuesta(request);
        }
        
        public string GetRespuesta(string clave) {
            WinServiceSICE.SICE.GetRespuestaRequest inValue = new WinServiceSICE.SICE.GetRespuestaRequest();
            inValue.Body = new WinServiceSICE.SICE.GetRespuestaRequestBody();
            inValue.Body.clave = clave;
            WinServiceSICE.SICE.GetRespuestaResponse retVal = ((WinServiceSICE.SICE.MetodosSoap)(this)).GetRespuesta(inValue);
            return retVal.Body.GetRespuestaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinServiceSICE.SICE.UploadComprobanteResponse WinServiceSICE.SICE.MetodosSoap.UploadComprobante(WinServiceSICE.SICE.UploadComprobanteRequest request) {
            return base.Channel.UploadComprobante(request);
        }
        
        public string UploadComprobante(string xml) {
            WinServiceSICE.SICE.UploadComprobanteRequest inValue = new WinServiceSICE.SICE.UploadComprobanteRequest();
            inValue.Body = new WinServiceSICE.SICE.UploadComprobanteRequestBody();
            inValue.Body.xml = xml;
            WinServiceSICE.SICE.UploadComprobanteResponse retVal = ((WinServiceSICE.SICE.MetodosSoap)(this)).UploadComprobante(inValue);
            return retVal.Body.UploadComprobanteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinServiceSICE.SICE.LoadComprobantesResponse WinServiceSICE.SICE.MetodosSoap.LoadComprobantes(WinServiceSICE.SICE.LoadComprobantesRequest request) {
            return base.Channel.LoadComprobantes(request);
        }
        
        public string LoadComprobantes(object objeto) {
            WinServiceSICE.SICE.LoadComprobantesRequest inValue = new WinServiceSICE.SICE.LoadComprobantesRequest();
            inValue.Body = new WinServiceSICE.SICE.LoadComprobantesRequestBody();
            inValue.Body.objeto = objeto;
            WinServiceSICE.SICE.LoadComprobantesResponse retVal = ((WinServiceSICE.SICE.MetodosSoap)(this)).LoadComprobantes(inValue);
            return retVal.Body.LoadComprobantesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WinServiceSICE.SICE.SaveEmpresaResponse WinServiceSICE.SICE.MetodosSoap.SaveEmpresa(WinServiceSICE.SICE.SaveEmpresaRequest request) {
            return base.Channel.SaveEmpresa(request);
        }
        
        public string SaveEmpresa(object objeto) {
            WinServiceSICE.SICE.SaveEmpresaRequest inValue = new WinServiceSICE.SICE.SaveEmpresaRequest();
            inValue.Body = new WinServiceSICE.SICE.SaveEmpresaRequestBody();
            inValue.Body.objeto = objeto;
            WinServiceSICE.SICE.SaveEmpresaResponse retVal = ((WinServiceSICE.SICE.MetodosSoap)(this)).SaveEmpresa(inValue);
            return retVal.Body.SaveEmpresaResult;
        }
    }
}
